### ISSUE TITLE
Embed Wasm engine using wasm-c-api

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#126] opened 2019-07-02 09:25 UTC
[wasm-c-api](https://github.com/WebAssembly/wasm-c-api)
> Provide[s] a "black box" API for embedding a Wasm engine in other C/C++ applications.

There should be prototypes of V8 implementing this interface, and hopefully also other Wasm engines; not sure if wabt, which we are currently using, also implements this.

This should also help with #74 (in fact I would say this is a prerequisite).

cc @hansman

**Comment by PiotrSikora** [comment] 2019-07-03 02:26
Note that as of v7.5 [wasm-c-api is included in V8](https://chromium.googlesource.com/v8/v8/+/refs/branch-heads/7.5/third_party/wasm-api/), and there are no other runtimes exposing this API, so this issue is effectively a duplicate of #74.

cc @jakobkummerow

**Comment by jakobkummerow** [comment] 2019-07-03 08:11
It is my (possibly incorrect) understanding that other runtimes (at least wabt and WAVM, maybe others) are either already working on implementing the wasm-c-api, or planning to; but I don't know any timelines.

At any rate, switching to the wasm-c-api sounds like a good idea; and so does switching to V8 IMHO :-)

**Comment by hansman** [comment] 2019-07-11 09:33
If the wasm-c-api is implemented in V8 only, probably we can use this issue as a first import of the V8 engine replacing wabt. Each enclave would run a V8 instance using the existing design before switching over to V8 isolates as described in https://github.com/project-oak/oak/issues/74.

**Closed** 2022-01-20 22:11 UTC
Labels: good first issue, lang/C++
