### ISSUE TITLE
Check Wasm module reproducibility

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#704] opened 2020-03-16 18:59 UTC
We need to check if Oak Wasm modules have the same hash after a rebuild (reproducibility).
In order to check we need clear the Cargo cache before rebuilding (so it would not influence the build).
Also we should check the hash values of modules compiled on different machines.

It also could be done as a part of the CI, but it might affect the Cloud Build time, since we will be clearing Cargo cache for all applications.

cc @tiziano88

**Comment by ipetr0v** [comment] 2020-03-16 19:12
My `sha256sum` values for the `hello_world` example look as follows:
```shell
3b65e7dcfeec0e6c979e69176169e6c235f2fffb95afb818f5c37cb5c545908c  target/wasm32-unknown-unknown/release/hello_world.wasm
```
```shell
3b65e7dcfeec0e6c979e69176169e6c235f2fffb95afb818f5c37cb5c545908c  target/wasm32-unknown-unknown/release/hello_world.wasm
```
And the hash value from a different machine:
```shell
3b65e7dcfeec0e6c979e69176169e6c235f2fffb95afb818f5c37cb5c545908c  target/wasm32-unknown-unknown/release/hello_world.wasm
```
So everything looks fine.

**Comment by tiziano88** [comment] 2020-03-16 19:29
Great news!

**Comment by tiziano88** [comment] 2020-04-20 21:56
So actually #865 is a duplicate of this, but I guess I'll keep that open since it has a bit more context about the reproducibility issues.

**Closed by tiziano88** 2020-04-20 21:56 UTC
