### ISSUE TITLE
Create deployable Docker image

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#382] opened 2019-12-17 21:10 UTC
The image should be as minimal as possible, and only contain the main [Oak server binary](https://github.com/project-oak/oak/blob/ad485a84f4095f69bd4e599f4cf30b31980761f3/oak/server/asylo/BUILD#L130-L144) and the enclave binary, plus any necessary parts of the intel SGX toolkit. It should be able to run both the simulated and the real SGX (if available on the physical machine). Note that the base Asylo image that we use currently is not ideal for this, as it has too many additional tools and dependencies installed, but maybe we can reuse the first few Docker steps from it to install the Intel SGX on an empty image.

I am not sure whether we should use Bazel to build the image (via https://github.com/bazelbuild/rules_docker#container_image-1), or do it via a regular Dockerfile.

There are interesting questions about signing the enclave binary: even though we do not rely on `MRSIGNER` at all in Oak, it seems that SGX requires the enclave binary to be signed. We may sign it with a key that we keep internal in Google, or, if we are sure we will never actually rely on it, we should consider creating a private key and checking it in this repository, and use it to sign enclave binaries just for the sake of making SGX happy. @annasapek @keithmoyer or is this a bad idea?

**Comment by annasapek** [comment] 2019-12-17 21:24
If you don't plan on relying on MRSIGNER at all ever, then you can manage your signing key however you want. You could even use the enclave created by Asylo's `sgx.debug_enclave` rule. This rule signs the enclave using Asylo's "debug signing key" (the private key is checked in [here](https://github.com/google/asylo/blob/v0.5.0/asylo/distrib/sgx_x86_64/enclave_test_pem.patch)).

**Comment by tiziano88** [comment] 2019-12-17 21:26
Thanks for confirming, that makes sense, though I thought that `sgx.debug_enclave` also sets other bits on the enclave binary that we may want to change, or can everything be controlled via `sgx.enclave_configuration`?

https://github.com/project-oak/oak/blob/ad485a84f4095f69bd4e599f4cf30b31980761f3/oak/server/asylo/BUILD#L71-L76

**Comment by annasapek** [comment] 2019-12-17 21:38
`sgx.debug_enclave` does use a [default `sgx.enclave_configuration`](https://github.com/google/asylo/blob/214e6c2f21ad23592b7eeb94c56f15dae9f8652d/asylo/distrib/sgx_x86_64/linux_sgx_2_6.patch#L5214-L5245) for signing, but yes, you can override any of the defaults by passing a custom `sgx.enclave_configuration` via the `config` field.

The use of `debug` in the name `sgx.debug_enclave` is a bit confusing--it simply refers to Asylo's debug signing key. @deeglaze can probably confirm that this is the intended interpretation of the name.

**Comment by deeglaze** [comment] 2019-12-17 21:57
The "debug" naming is indeed to point out that any automated signing process in a run-of-the-mill BUILD file is insecure and should not be used for release enclaves. We do have non-debug rules that can be used carefully (e.g. boringssl_sign_enclave_signing_material), but access to a private key should be closely guarded - the signing rule should not build in arbitrary environments.

We have another rule, `sgx_signed_enclave`, that is safe to use but is very brittle. If a signature is committed to the code base, it is only valid for a specific enclave measurement. If any bits of the enclave binary change, then the signature becomes invalid. Thus, in a reproducible build, any user should be able to reproduce the enclave bits and successfully apply the signature.

**Comment by tiziano88** [comment] 2019-12-18 20:12
Thanks @deeglaze , that makes sense, except that in our case we *will* use the output of `debug_enclave` as the release enclave, because we intentionally do not care about `MRSIGNER` at all. In fact if there was a way of zeroing out `MRSIGNER`, we would probably use that, but I don't think there is.

**Comment by deeglaze** [comment] 2019-12-18 20:48
That really surprises me. I'm willing to consider renaming the rule to be less judgmental about the build-system-accessibility of the private key, but I'd like to understand the justification for it. Do you have some documentation I could read to get context?

**Comment by tiziano88** [comment] 2019-12-18 20:54
In short, if we rely on `MRSIGNER` at all as part of the remote attestation, then whoever holds the signing key would be able to create a new version of the enclave with a backdoor, sign it, deploy it, and still pass any remote attestation validation from clients, and in this way compromise the security of the entire system. The backdoored enclave code does not need to ever be published, and may be kept secret and used for targeted attacks, which we are trying to avoid. 

Instead for Oak we specifically only want to rely on code identity (i.e. `MRENCLAVE`). The short term plan is to hardcode a set of "valid" `MRENCLAVE` values in the client, but longer term we would like to require logging valid values of `MRENCLAVE` to a verifiable log (probably https://github.com/google/trillian), effectively implementing a "binary transparency" log of allowed `MRENCLAVE` values, and have clients check for the presence of the remote `MRENCLAVE` value in such log (or, ideally, more than one such logs).

Does this make sense, at a high level?

**Comment by deeglaze** [comment] 2019-12-18 21:03
Is your plan then hardcoding these MRENCLAVE values into a provisioning enclave as well? How do you plan to launch these enclaves?

**Comment by tiziano88** [comment] 2019-12-18 23:02
I am not aware of that requirement, could you elaborate? Would we need to implement such provisioning enclave ourselves? Or just provide a configuration for it? We just want to launch enclaves regardless of their `MRENCLAVE` or `MRSIGNER`.

**Comment by tiziano88** [comment] 2019-12-18 23:03
My understanding talking with @annasapek is that Asylo would provide some sort of enclave launcher / quoting enclave, but I am not sure it is the same as the one you are describing.

**Comment by deeglaze** [comment] 2019-12-18 23:04
Launching any enclave regardless of any authorization is a malware vector. I recommend that you investigate the parameters of Intel's Flexible Launch Control (FLC) extensions for SGX2.

**Comment by tiziano88** [comment] 2019-12-18 23:07
Not sure I follow: assuming we want to run our enclave on a cloud machine (physical or virtual) that we control, what is the risk? that someone would swap the enclave binary for one that contains malware, and we would accidentally run that? I don't see how that is different from the same argument for a standard binary though.

**Comment by deeglaze** [comment] 2019-12-18 23:23
Okay, assuming Google controls the machines, then you shouldn't have to worry about launching the enclaves. We'll figure that part out.

**Closed** 2019-12-19 19:09 UTC
